steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/reservations/production',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/payment/production',
        '-f',
        'apps/payment/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/payment/production',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/notification/production',
        '-f',
        'apps/notification/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/notification/production',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/project-b8052276-494f-4d76-a76/auth/production',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
